DATA_SOURCE_TWITTER_API = 'twitter_official'
DATA_SOURCE_TWITTER_SCRAPER = 'twitter_scraper'
DATA_SOURCE_TWEEPY = 'tweepy'

OUR_DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S'

DEFAULT_USER_TWEETS_LIMIT = 100
DEFAULT_SEARCH_LIMIT = 300
DEFAULT_TWEET_REPLY_LIMIT = 100

USA_WOEID = 23424977