# Generated by Django 2.1.2 on 2018-11-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_term', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.IntegerField(unique=True)),
                ('screen_name', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('toxicity', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.Tweet'),
        ),
    ]
