# Generated by Django 2.1.2 on 2018-11-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('topic_term', 'tweet')},
        ),
    ]
