# Generated by Django 2.1.2 on 2018-11-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_auto_20181126_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='topics',
            field=models.ManyToManyField(related_name='tweets', to='clientapp.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_term',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tweet',
        ),
    ]
